<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <RootNamespace>MatrixShader.Lite</RootNamespace>
    <!-- Enable AOT compatibility analyzer -->
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MatrixShader.Core\MatrixShader.Core.csproj" />
  </ItemGroup>

</Project>
